name: Push to separate branch

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # the checkout action persists the passed credentials by default
    # subsequent git commands will pick them up automatically
    - uses: actions/checkout@v2
    - run: |
        # do something
        echo "${{github.event.head_commit.message}}"
        git config user.email "georgeselly@yahoo.com"
        git config user.name "George Selly"
        branch_name=$(echo "${{github.event.head_commit.message}}" | head -n 1 | awk '{print $1}')
        echo "$branch_name"
        git fetch origin main:main
        git switch main
        git checkout $branch_name 2>/dev/null || git checkout -b $branch_name
        git cherry-pick development
